name: Checks

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'DueDine/DLP-Cado'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies & Clone repo
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y build-essential make cmake libgmp-dev
          git clone https://gitlab.inria.fr/cado-nfs/cado-nfs.git
      - name: Cache build
        id: cache
        uses: actions/cache@v3
        with:
          path: cado-nfs/build
          key: ${{ runner.os }}-caches
      - name: Rename build
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          cd cado-nfs/build
          mv $(ls .) $(hostname)
      - name: Make cado
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd cado-nfs
          make
      - name: Run Python
        run: python check.py
