name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y build-essential make cmake libgmp-dev
    - name: Cado works
      run: |
        git clone https://gitlab.inria.fr/cado-nfs/cado-nfs.git
        cd cado-nfs
        make
    - name: Run Python
      run: |
        python dlp.py
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./ret.txt
        if-no-files-found: error